export const GET_LIST_LEAGUES = "GET_LIST_LEAGUES";
export const GET_LIST_LEAGUES_FAILURE = "GET_LIST_LEAGUES_FAILURE";
export const GET_LIST_LEAGUES_SUCCESS = "GET_LIST_LEAGUES_SUCCESS";

export const GET_LIST_UPCOMMING_EVENTS = "GET_LIST_UPCOMMING_EVENTS";
export const GET_LIST_UPCOMMING_EVENTS_FAILURE = "GET_LIST_UPCOMMING_EVENTS_FAILURE";
export const GET_LIST_UPCOMMING_EVENTS_SUCCESS = "GET_LIST_UPCOMMING_EVENTS_SUCCESS";

export const GET_LIST_CREATED_LEAGUES = "GET_LIST_CREATED_LEAGUES";
export const GET_LIST_CREATED_LEAGUES_FAILURE = "GET_LIST_CREATED_LEAGUES_FAILURE";
export const GET_LIST_CREATED_LEAGUES_SUCCESS = "GET_LIST_CREATED_LEAGUES_SUCCESS";

export const GET_LIST_JOINED_LEAGUE = "GET_LIST_UPCOMMING_EVENTS";
export const GET_LIST_JOINED_LEAGUE_FAILURE = "GET_LIST_JOINED_LEAGUE_FAILURE";
export const GET_LIST_JOINED_LEAGUE_SUCCESS = "GET_LIST_JOINED_LEAGUE_SUCCESS";

export const UPDATE_DEVICE_TOKEN = "UPDATE_DEVICE_TOKEN";
export const UPDATE_DEVICE_TOKEN_SUCCESS = "UPDATE_DEVICE_TOKEN_SUCCESS";
export const UPDATE_DEVICE_TOKEN_FAILURE = "UPDATE_DEVICE_TOKEN_FAILURE";
